# Generated by Django 4.1.1 on 2022-10-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_remove_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='ddff', upload_to='pic'),
            preserve_default=False,
        ),
    ]
